lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DiscussWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser

    resources "/topics", TopicController
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    put "/signout", AuthController, :signout
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DiscussWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/discuss/application.ex
defmodule Discuss.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Discuss.Repo,
      # Start the Telemetry supervisor
      DiscussWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Discuss.PubSub},
      # Start the Endpoint (http/https)
      DiscussWeb.Endpoint
      # Start a worker by calling: Discuss.Worker.start_link(arg)
      # {Discuss.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/comment/comment.ex
defmodule Discuss.Comment do
  use Ecto.Schema

  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:content, :user]}
  schema "comments" do
    field :content, :string
    belongs_to :user, Discuss.User
    belongs_to :topic, Discuss.Topic

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content])
    |> validate_required([:content])
  end
end

lib/discuss/mailer.ex
defmodule Discuss.Mailer do
  use Swoosh.Mailer, otp_app: :discuss
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo,
    otp_app: :discuss,
    adapter: Ecto.Adapters.Postgres
end

lib/discuss/topic/topic.ex
defmodule Discuss.Topic do
  use Ecto.Schema

  import Ecto.Changeset

  schema "topics" do
    field :title, :string
    belongs_to :user, Discuss.User
    has_many :comments, Discuss.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end
end

lib/discuss/user/user.ex
defmodule Discuss.User do
  use Ecto.Schema

  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:email]}
  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end
end

lib/discuss_web/controllers/auth_controller.ex
defmodule DiscussWeb.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth

  alias Discuss.User
  alias Discuss.Repo

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, _params) do
    user_params = %{
      token: auth.credentials.token,
      email: auth.info.email,
      provider: to_string(auth.provider)
    }

    %User{}
    |> User.changeset(user_params)
    |> signin(conn)
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: Routes.topic_path(conn, :index))
  end

  defp signin(changeset, conn) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> put_session(:user_id, user.id)
        |> redirect(to: Routes.topic_path(conn, :index))

      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Error signing in")
        |> redirect(to: Routes.topic_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil ->
        Repo.insert(changeset)

      user ->
        {:ok, user}
    end
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  import Ecto

  alias Discuss.Repo
  alias Discuss.Topic

  plug DiscussWeb.Plugs.RequireAuth
       when action in [
              :new,
              :create,
              :edit,
              :update,
              :delete
            ]

  plug :check_topic_owner
       when action in [
              :edit,
              :update,
              :delete
            ]

  def index(conn, _params) do
    topics = Repo.all(Topic)
    render(conn, "index.html", topics: topics)
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render(conn, "show.html", topic: topic)
  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"topic" => topic}) do
    changeset =
      conn.assigns.user
      |> build_assoc(:topics)
      |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic created!")
        |> redirect(to: Routes.topic_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)
    render(conn, "edit.html", changeset: changeset, topic: topic)
  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(old_topic, topic)

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Updated!")
        |> redirect(to: Routes.topic_path(conn, :index))

      {:error, changeset} ->
        render(conn, "edit.html", changeset: changeset, topic: old_topic)
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    Topic
    |> Repo.get!(topic_id)
    |> Repo.delete!()

    conn
    |> put_flash(:info, "Topic Deleted!")
    |> redirect(to: Routes.topic_path(conn, :index))
  end

  defp check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id}} = conn

    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You're not authorized to do that!")
      |> redirect(to: Routes.topic_path(conn, :index))
      |> halt()
    end
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/discuss_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/discuss_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Discuss", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css" )} />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js" )}></script>
  <script>
    <%= if @conn.assigns.user do %>
      window.userToken = '<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>'
    <% end %>
  </script>
</head>

<body>
  <nav class="light-blue">
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">
        Discussions
      </a>
      <ul class="right">
        <%= if @conn.assigns[:user] do %>
        <li>
          <%= link "Sign Out", to: Routes.auth_path(@conn, :signout), method: :put %>
        </li>
        <% else %>
        <li>
          <%= link "Sign in with GitHub", to: Routes.auth_path(@conn, :request, "github") %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <header>
    <section class="container">

    </section>
  </header>
  <%= @inner_content %>
</body>

</html>

lib/discuss_web/templates/topic/edit.html.heex
<%= form_for @changeset, Routes.topic_path(@conn, :update, @topic), fn f -> %>
<div class="form-group">
  <%= text_input f, :title, placeholder: Title, class: "form-control" %>
  <%= error_tag f, :title %>
</div>

<%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/index.html.heex
<h2>Topics</h2>

<ul class="collection">
  <%= for topic <- @topics do %>
  <li class="collection-item">
    <%= link topic.title, to: Routes.topic_path(@conn, :show, topic) %>
    <%= if @conn.assigns.user.id == topic.user_id do %>
    <div class="right">
      <%= link "Edit", to: Routes.topic_path(@conn, :edit, topic) %>
      <span>|</span>
      <%= link "Delete", to: Routes.topic_path(@conn, :delete, topic), method: :delete %>
    </div>
    <% end %>
  </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: Routes.topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
  <i class="material-icons">add</i>
  <% end %>
</div>

lib/discuss_web/templates/topic/new.html.heex
<%= form_for @changeset, Routes.topic_path(@conn, :create), fn f -> %>
<div class="form-group">
  <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
  <%= error_tag f, :title %>
</div>

<%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/show.html.heex
<h5><%= @topic.title %></h5>
<div class="input-field">
  <textarea class="materialize-textarea"></textarea>
  <button class="btn">Add Comment</button>
  <ul class="collection">
  </ul>
</div>

<script>
  document.addEventListener("DOMContentLoaded", () => window.joinChannel( <%= @topic.id %> ))
</script>